# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.provider :libvirt do |machine|
      machine.cpus = 2
      machine.memory = 2048
  end
  
  config.vm.provider :virtualbox do |machine|
      machine.cpus = 2
      machine.memory = 2048
  end

  config.vm.define "agent1" do |agent1|
      agent1.vm.box = "centos/7"
      agent1.vm.hostname = "agent1"
      agent1.vm.network :private_network, ip: "192.168.56.50"
  end

  config.vm.define "agent2" do |agent2|
    agent2.vm.box = "generic/ubuntu1604"
    agent2.vm.hostname = "agent2"
    agent2.vm.network :private_network, ip: "192.168.56.51"
end

  config.vm.provision "shell" do |s|
      ssh_dir = ENV["HOME"] + "/.ssh/id_rsa.pub"
      ssh_pub_key = File.readlines(ssh_dir).first.strip
      s.inline = <<-SHELL
        mkdir /root/.ssh/ && touch /root/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
      SHELL
  end

## Provision both VMs using Ansible after the last VM is booted.
#    config.vm.provision "ansible" do |ansible|
#      ansible.playbook = "playbooks/kube-dependencies.yml"
#      ansible.inventory_path = "playbooks/hosts"
#      ansible.limit = "all"
#    end
  
end