---

- name: delete_agent | CentOS 7
  include: delete_agent_centos.yml
  when:
    - (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")

- name: delete_agent | Ubuntu
  include: delete_agent_ubuntu.yml
  when:
    - (ansible_facts['distribution'] == "Ubuntu")
