---

- name: Install check mk rpm from local repository | CentOS 7
  yum: 
    name: "{{ check_mk_rpm_url }}"
    state: present
    update_cache: yes

- name: Ensure that the core packages are installed | CentOS 7
  yum: 
    name: "{{ install_agent_packages_centos }}"
    state: present
    update_cache: yes

- name: Create cache and scripts directory | CentOS 7
  file:
    path: "{{ item }}"
    state: directory
    mode: "755"
  with_items:
    - '/var/lib/check_mk_agent/cache/'
    - '/usr/lib/check_mk_agent/scrips'

- name: Copy all needed files to the target host | CentOS 7
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: no
    mode: "755"
  with_items:
    - { src: 'centos/plugins/', dest: '/usr/lib/check_mk_agent/plugins/'}
    - { src: 'centos/local/', dest: '/usr/lib/check_mk_agent/local/' }
    - { src: 'configs/logwatch.cfg', dest: '/etc/check_mk/logwatch.cfg' }
    - { src: 'configs/encryption.cfg', dest: '/etc/check_mk/encryption.cfg' }
#    - { src: 'centos/lib/host_register.sh', dest: '/usr/lib/check_mk_agent/scripts/host_register.sh' }

- name: Populate sevice facts
  service_facts:

- name: Allow tcp port "{{ check_mk_server }}" firewalld | CentOS 7
  firewalld:
    port: "6556/tcp"
    #source: "{{ firewalld_zones }}"
    permanent: yes
    immediate: yes
    state: enabled
  become: yes
  when: ansible_facts['services']['firewalld.service']['state'] == "running"
#    - (ansible_facts.services and ansible_facts.services['firewalld.service'].status == "enabled")
#    - "'firewalld.service' in ansible_facts.services and ansible_facts.services['firewalld.service'].status == 'enabled'"

#- name: Stop and disable Firewalld
#  service:
#    name: firewalld
#    state: stopped
#    enabled: no

#- name: Allow tcp port "{{ check_mk_server }}" firewalld | CentOS 7
#  firewalld:
#    zone: public
#    port: "6556/tcp"
#    permanent: true
#    state: enabled
#  become: yes

#- name: Register the Server | CentOS 7
#  shell: "/usr/lib/check_mk_agent/scripts/host_register.sh -u autouser -f discovered_phx -p {{ mk_pass }}"
